### ISSUE TITLE
connect eris-contracts.js to eris-keys

### ISSUE THREAD

**Issue by compleatang** [monax/legacy-contracts.js#23]
This temporary hack needs to get fixed and having eris-contracts.js talk to eris-keys via eris-keys.js is a necessity. 

![screenshot-docs erisindustries com 2016-03-10 23-30-14](https://cloud.githubusercontent.com/assets/590037/13686867/45d64378-e718-11e5-89ed-73ea43f27ba3.png)

**Comment by NodeGuy** [comment]
This will be part of the API rewrite.
