### ISSUE TITLE
Event subscription is returning an error and event callback is not triggering behind a corporate proxy

### ISSUE THREAD

**Issue by sathishmanoharan** [monax/legacy-contracts.js#71]
# Version Numbers

Fill in version numbers below.

* Node.js: v6.2.2
* Eris CLI: 0.12.0 (002c63e)
* eris-contracts: 0.15.8

# Issue Description

Event subscription is returning an error and event callback is not triggering behind a corporate proxy.
# Code

Include all code and data needed to reproduce the problem by replacing the examples below.

## Solidity

```Solidity
contract Test {
event notify(bytes32 val1, bytes32 val2, string val3, uint val4));
function eventTest() {
notify(val1,val2,val3,val4);
}
}

## JavaScript

```JavaScript
var eventListener = function() {
  this.chain = 'dmchain_full_000';
  this.erisdburl = "http://localhost:1337/rpc";
  this.contractData = require("./jobs_output.json");
  this.contractAddress = this.contractData['deployStorageK'];
  this.erisAbi = JSON.parse(fs.readFileSync("./abi/" + this.contractAddress));
  this.accountData = require("./accounts.json");
  this.contractMgr = erisContracts.newContractManagerDev(this.erisdburl, this.accountData[this.chain]);
  this.testContract = this.contractMgr.newContractFactory(this.erisAbi).at(this.contractAddress);

  var notifyOwnerResult;
  console.log("eventListener initialized");

  this.testContract.notifyOwner(
      function (error, result)
      {
        if(error) {
          console.log("error from notifyOwner subscription", error);
        }
        else {
          console.log("notify owner event triggered - start callback");
          console.log(error,result);
        }
      },
      function (error, result) {
        console.log(error,result);
        console.log("notify owner event triggered - event callback");
        //grab parameters from the event
        var proposalId = result.args.requesterPubkey;
        var votingResult = result.args.ownerPubkey;
        var resultMessage = result.args.dimension;
        var coidGKAddr = result.args.requesterSuggestedPrice;
        console.log(JSON.stringify(result.args));
      }
  );
}
var listening = new eventListener();
app.listen(3000, function () {
    console.log("Connected to contract http://localhost:1337/rpc");
    console.log("Listening on port 3000");
});
```
Starting the nodejs module produces the following response

![image](https://cloud.githubusercontent.com/assets/18713130/21984145/8a41470e-dc1a-11e6-887f-329141c0be75.png)

When I call the function that triggers the event, I dont see callback getting executed. But when I stop the chain, I am following error. 
![image](https://cloud.githubusercontent.com/assets/18713130/21984298/4c027750-dc1b-11e6-9867-e4ef78acaa38.png)

I am behind corporate proxy and I have configured proxy details in npm config and /etc/environment. I am able to get response from other eris-db api's like /accounts in browser. The error text 'Call of eris db method' is coming from server.js and it is doing something with proxy. Is there a problem related to proxy? 

![image](https://cloud.githubusercontent.com/assets/18713130/21984559/7b4455f0-dc1c-11e6-9634-21aa01ca5ae3.png)

**Comment by dharmesh-kh24** [comment]
I faced the same error.
Make sure **http_proxy** and **https_proxy** is NOT in environment variables. Instead, add proxy and https_proxy in `%USERPROFILE%/.npmrc`.
Contents of .npmrc file:
```
proxy=http://ip:port/
https-proxy=http://ip:port/
strict-ssl=false
registry=http://registry.npmjs.org/
rejectUnauthorized=false
```

**Comment by NodeGuy** [comment]
Thank you, @dharmesh-kh24.  @sathishmanoharan, does his suggestion solve your problem?
